# Generated by Django 2.2.3 on 2019-07-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='description',
        ),
        migrations.AddField(
            model_name='poll',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
